# build_binary:
#     builder: 'particle photon'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware && echo "nikolas"

testing:
   script: testing/3.complex-tests/disable-wifi-and-test-functionality.py
   env_vars: 
       - $IFTTT_API_KEY
       - $SPN_PARTICLE_TOKEN
#     env_vars:
#         - $SPN_PARTICLE_TOKEN
#        ota_method: particle
#        binary: auto
